apiVersion: apps/v1
kind: Deployment
metadata:
  name: ion-deployment
  labels:
    app: ion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ion
  template:
    metadata:
      labels:
        app: ion
    spec:
      containers:
      - name: ion
        #image: ssadcloud/rion2:v3.0
        image: 932589472370.dkr.ecr.ap-south-1.amazonaws.com/rion-ecr:latest
        ports:
        - containerPort: 80
